In [1]:
import pandas as pd

In [4]:
alumnos = pd.read_csv("../data/estudiantes_478_registros.csv")
alumnos

     ID_estudiante   Sexo     Objetivo_principal
0                1  Niñas               Deportes
1                2  Niños  Buenas calificaciones
2                3  Niños            Popularidad
3                4  Niños  Buenas calificaciones
4                5  Niños  Buenas calificaciones
..             ...    ...                    ...
473            474  Niños  Buenas calificaciones
474            475  Niñas  Buenas calificaciones
475            476  Niñas  Buenas calificaciones
476            477  Niñas            Popularidad
477            478  Niños  Buenas calificaciones

[478 rows x 3 columns]

In [6]:
agrupacion = alumnos.groupby(["Sexo", "Objetivo_principal"]).size()
agrupacion

Sexo   Objetivo_principal
Niñas  Buenas calificaciones    130
       Deportes                  30
       Popularidad               91
Niños  Buenas calificaciones    117
       Deportes                  60
       Popularidad               50
dtype: int64

In [9]:
tabla = pd.crosstab(
    alumnos["Sexo"], alumnos["Objetivo_principal"],
    margins=True,
    margins_name= "Total"
)
tabla

Objetivo_principal  Buenas calificaciones  Deportes  Popularidad  Total
Sexo
Niñas                                 130        30           91    251
Niños                                 117        60           50    227
Total                                 247        90          141    478

### 4. 📊 Calcular probabilidades condicionales

Por ejemplo, ¿cuál es la probabilidad de que un estudiante quiera destacar en deportes, sabiendo que es niña?

**P(Deportes | Niña) = 30 / 251 ≈ 0.1195 = 11.95 %**

In [11]:
probabilidad = (
    tabla.loc["Niñas", "Deportes"]
    / tabla.loc["Niñas", "Total"]
)

print(f"Probabilidad: {probabilidad:.3f}")
print(f"Porcentaje: {probabilidad:.1%}")

Probabilidad: 0.120
Porcentaje: 12.0%